[hekad]
maxprocs = 4
base_dir = "."
share_dir = "."
max_timer_inject = 100
max_process_duration = 1000000

[ProtobufDecoder]
encoding_name = "PROTOCOL_BUFFER"

[TCP:5565]
type = "TcpInput"
parser_type = "message.proto"
decoder = "ProtobufDecoder"
address = ":5565"
	[TCP:5565.signer.telemetry_0]
	hmac_key = "TODO change on deploy" # TODO update on deploy

[TelemetrySandboxManager]
type = "SandboxManagerFilter"
message_signer = "telemetry"
message_matcher = "Type == 'heka.control.sandbox'"
max_filters = 10

[AMQPInput]
url = "amqp://guest:guest@10.250.68.186"
exchange = "testout"
exchangeType = "fanout"
decoder="ProtobufDecoder"

[Dashboard]
type = "DashboardOutput"
address = ":4352"
ticker_interval = 10

[TelemetryServerMetricsAggregator]
type = "SandboxFilter"
message_matcher = "Logger == 'TelemetryServerMetrics' && Fields[payload_type] == 'cbufd'"
ticker_interval = 60
script_type = "lua"
filename = "lua_filters/cbufd_aggregator.lua"
preserve_data = true

[TelemetryServerMetricsHostAggregator]
type = "SandboxFilter"
message_matcher = "Logger == 'TelemetryServerMetrics' && Fields[payload_type] == 'cbufd'"
ticker_interval = 60
script_type = "lua"
filename = "lua_filters/cbufd_host_aggregator.lua"
preserve_data = true

[TelemetryServerMetricsHostAggregator.config]
max_hosts = 10
rows = 60

[TelemetryChannelMetricsAggregator]
type = "SandboxFilter"
message_matcher = "Logger == 'TelemetryChannelMetrics' && Fields[payload_type] == 'cbufd'"
ticker_interval = 60
script_type = "lua"
filename = "lua_filters/cbufd_aggregator.lua"
preserve_data = true

[TelemetryChannelMetricsAggregator.config]
alert_rows = 15
alert_cols = '[{"col":1, "deviation":1.5}]'

[TelemetryChannelMetrics60DaysAggregator]
type = "SandboxFilter"
message_matcher = "Logger == 'TelemetryChannelMetrics60Days' && Fields[payload_type] == 'cbufd'"
ticker_interval = 60
script_type = "lua"
filename = "lua_filters/cbufd_aggregator.lua"
preserve_data = true

[TelemetryChannelMetrics60DaysAggregatorAlerting]
type = "SandboxFilter"
message_matcher = "Logger == 'TelemetryChannelMetrics60Days' && Fields[payload_type] == 'cbufd'"
ticker_interval = 60
script_type = "lua"
filename = "lua_filters/cbufd_aggregator.lua"
preserve_data = true

[TelemetryChannelMetrics60DaysAggregatorAlerting.config]
alert_rows = 15
alert_cols = '[{"col":1, "deviation":1.5}]'

[TelemetryConvertMetrics]
type = "SandboxFilter"
message_matcher = "Type == 'telemetry.convert'"
ticker_interval = 60
script_type = "lua"
filename = "lua_filters/telemetry_convert.lua"
preserve_data = true

[TelemetryAlert]
type = "SmtpOutput"
payload_only = false
message_matcher = "Type == 'heka.sandbox-output' && Fields[payload_type] == 'alert'"
send_to = ["telemetry-alerts@mozilla.com"]
host = "mozilla.com.s5a1.psmtp.com:25"

[TelemetryStatsRecordsAggregator]
type = "SandboxFilter"
message_matcher = "Logger == 'TelemetryStatsRecords' && Fields[payload_type] == 'cbufd'"
ticker_interval = 60
script_type = "lua"
filename = "lua_filters/cbufd_aggregator.lua"
preserve_data = true

[TelemetryStatsBytesAggregator]
type = "SandboxFilter"
message_matcher = "Logger == 'TelemetryStatsBytes' && Fields[payload_type] == 'cbufd'"
ticker_interval = 60
script_type = "lua"
filename = "lua_filters/cbufd_aggregator.lua"
preserve_data = true

[TelemetryStatsErrorsAggregator]
type = "SandboxFilter"
message_matcher = "Logger == 'TelemetryStatsErrors' && Fields[payload_type] == 'cbufd'"
ticker_interval = 60
script_type = "lua"
filename = "lua_filters/cbufd_aggregator.lua"
preserve_data = true
