[hekad]
maxprocs = 4
max_timer_inject = 100
max_process_duration = 1000000

[TCP:5565]
type = "TcpInput"
parser_type = "message.proto"
decoder = "ProtobufDecoder"
address = ":5565"
	[TCP:5565.signer.telemetry_0]
	hmac_key = "TODO change on deploy" # TODO update on deploy

[TelemetrySandboxManager]
type = "SandboxManagerFilter"
message_signer = "telemetry"
message_matcher = "Type == 'heka.control.sandbox'"
max_filters = 10

[Dashboard]
type = "DashboardOutput"
address = ":4352"
ticker_interval = 15

[TcpOutput]
address = "heka.shared.us-west-2.prod.mozaws.net:5565"
use_tls = true
message_matcher =  "Type == 'heka.sandbox-output' && Fields[payload_type] == 'cbufd'"

[TcpOutput.tls]
insecure_skip_verify = false
