[hekad]
maxprocs = 4
base_dir = "."
max_timer_inject = 100
max_process_duration = 500000

[ProtobufDecoder]
encoding_name = "PROTOCOL_BUFFER"

[TCP:5565]
type = "TcpInput"
parser_type = "message.proto"
decoder = "ProtobufDecoder"
address = ":5565"
	[TCP:5565.signer.telemetry_0]
	hmac_key = "TODO change on deploy" # TODO update on deploy

[TelemetrySandboxManager]
type = "SandboxManagerFilter"
message_signer = "telemetry"
message_matcher = "Type == 'heka.control.sandbox'"
working_directory = "sandbox"
max_filters = 10

[TelemetryServerInput]
type = "LogfileInput"
logfile = "/var/log/telemetry/telemetry-server.log"
decoder = "TelemetryServerDecoder"
seek_journal_name = "telemetry-server.journal"
use_seek_journal = true 

[TelemetryServerDecoder]
type = "SandboxDecoder"
script_type = "lua"
filename = "telemetry_server_decoder.lua"
module_directory = "/usr/share/heka/lua_modules"

[TelemetryServerMetrics]
type = "SandboxFilter"
message_matcher = "Type == 'TelemetryServerLog'"
ticker_interval = 60
script_type = "lua"
filename = "telemetry_server_metrics.lua"
preserve_data = true
memory_limit = 1000000 
instruction_limit = 1000
output_limit = 64000

[TelemetryChannelMetrics]
type = "SandboxFilter"
message_matcher = "Type == 'TelemetryServerLog'"
ticker_interval = 60
script_type = "lua"
filename = "telemetry_channel_metrics.lua"
preserve_data = true
memory_limit = 8000000 
instruction_limit = 1000
output_limit = 64000

[TelemetryChannelMetrics.config]
rows = 1440
sec_per_row = 60

[TelemetryChannelMetrics60Days]
type = "SandboxFilter"
message_matcher = "Type == 'TelemetryServerLog'"
ticker_interval = 60
script_type = "lua"
filename = "telemetry_channel_metrics.lua"
preserve_data = true
memory_limit = 8000000
instruction_limit = 1000
output_limit = 64000

[TelemetryChannelMetrics60Days.config]
rows = 1440
sec_per_row = 3600

[Dashboard]
type = "DashboardOutput"
address = ":4352"
ticker_interval = 10
working_directory = "dashboard"
static_directory = "/usr/share/heka/dasher"

[AMQPOutput]
url = "amqp://guest:guest@10.250.68.186"
exchange = "testout"
exchangeType = "fanout"
message_matcher =  "Type == 'heka.sandbox-output' && Fields[payload_type] == 'cbufd'"
